apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: demo-loan-nn-onnx-alpha
  annotations:
    serving.kserve.io/deploymentMode: ModelMesh
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
      runtime: ovms-1.x
      storageUri: "https://github.com/robgeada/trustyai-explainability/blob/RHODS-8036/e2e_tests/resources/biased_models/loan_model_alpha.onnx?raw=true"