name: Build and Push
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
jobs:
  # Ensure that tests pass before publishing a new image.
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Pull prerequisite images
        uses: ./.github/actions/pull_prerequisites
      - name: Build and Push
        uses: ./.github/actions/quay_image_build_and_push
        with:
          image-name: quay.io/trustyai/trustyai-service
          tag:  latest
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_SECRET }}